steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/melodic-lantern-392521/tritris', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/melodic-lantern-392521/tritris']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'tritris', '--image', 'gcr.io/melodic-lantern-392521/tritris', '--region', 'us-central1', '--platform', 'managed']
