steps:
  - name: 'gcr.io/cloud-builders/gradle'
    args: ['clean', 'build', '--warning-mode', 'all']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'my-app', '--image', 'gcr.io/$PROJECT_ID/my-app', '--region', 'us-central1', '--platform', 'managed']
