steps:
    # Build the container image
    - name: "gcr.io/cloud-builders/docker"
      args: ["build", "-t", "gcr.io/$PROJECT_ID/myapi:$COMMIT_SHA", "."]
    # Push the container image to Container Registry
    - name: "gcr.io/cloud-builders/docker"
      args: ["push", "gcr.io/$PROJECT_ID/myapi:$COMMIT_SHA"]
    # Deploy container image to Cloud Run
    - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
      entrypoint: gcloud
      args:
          - "run"
          - "deploy"
          - "myapi"
          - "--image"
          - "gcr.io/$PROJECT_ID/myapi:$COMMIT_SHA"
          - "--region"
          - "asia-east1"
images:
    - "gcr.io/$PROJECT_ID/myapi:$COMMIT_SHA"