/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dstris;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        assertNotNull(false, "app should have a greeting");
    }
}
